apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: enmasse
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafana-config
          readOnly: true
        - mountPath: /etc/grafana/dashboards
          name: grafana-dashboards
          readOnly: true
        - mountPath: /usr/share/grafana/data
          name: grafana-data
        readOnly: false
        env:
        - name: GF_INSTALL_PLUGINS
          value: "camptocamp-prometheus-alertmanager-datasource,grafana-kubernetes-app"
        - name: GF_PATHS_DATA
          value: /usr/share/grafana/data
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
          items:
          - key: dashboard.yaml
            path: dashboards/dashboard.yaml
          - key: datasource.yaml
            path: datasources/datasource.yaml
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
