apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      evaluation_interval: 60s
      scrape_interval: 60s
    rule_files:
    - rules.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    scrape_configs:
      - job_name: 'artemis_pod_job'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: artemismetrics.*
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
      - job_name: 'router_pod_job'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: routermetrics.*
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
      - job_name: component_health
        kubernetes_sd_configs:
        - role: service
        metrics_path: "/sys/info/metrics"
        relabel_configs:
        - action: keep
          regex: http.*
          source_labels: [__meta_kubernetes_service_port_name]
        - action: replace
          source_labels: [__meta_kubernetes_service_name]
          target_label: kubernetes_pod_name